import json as json_module
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

from rich.console import Console
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn, TimeElapsedColumn
from rich.tree import Tree

from lattice.infrastructure.postgres.postgres import PostgresClient
from lattice.metadata.api import GenerationProgress, MetadataGenerator, MetadataRepository
from lattice.projects.api import ProjectManager


async def run_metadata_show(name: str, field: str | None = None, as_json: bool = False) -> None:
    console = Console()

    try:
        async with PostgresClient() as postgres:
            repository = MetadataRepository(postgres)
            metadata = await repository.get_by_project_name(name)
    except Exception as e:
        console.print(f"[red]Error connecting to PostgreSQL: {e}[/red]")
        console.print("[yellow]Make sure Docker containers are running.[/yellow]")
        sys.exit(1)

    if not metadata:
        console.print(f"[red]No metadata found for project '{name}'.[/red]")
        console.print("[dim]Run 'lattice index <path>' to generate metadata.[/dim]")
        sys.exit(1)

    if as_json:
        output: dict[str, Any] = {
            "project_name": metadata.project_name,
            "version": metadata.version,
            "status": metadata.status.value,
            "generated_by": metadata.generated_by,
            "generation_model": metadata.generation_model,
            "generation_duration_ms": metadata.generation_duration_ms,
            "created_at": metadata.created_at.isoformat() if metadata.created_at else None,
            "updated_at": metadata.updated_at.isoformat() if metadata.updated_at else None,
        }

        if not field or field == "overview":
            output["project_overview"] = metadata.project_overview
        if not field or field == "features":
            output["core_features"] = [f.model_dump() for f in metadata.core_features]
        if not field or field == "architecture":
            output["architecture_diagram"] = metadata.architecture_diagram
        if not field or field == "tech":
            output["tech_stack"] = metadata.tech_stack.model_dump() if metadata.tech_stack else None
        if not field or field == "deps":
            deps = metadata.dependencies.model_dump() if metadata.dependencies else None
            output["dependencies"] = deps
        if not field or field == "entry":
            output["entry_points"] = [e.model_dump() for e in metadata.entry_points]
        if not field or field == "folders":
            folders = metadata.folder_structure.model_dump() if metadata.folder_structure else None
            output["folder_structure"] = folders

        console.print(json_module.dumps(output, indent=2))
        return

    duration = f"{metadata.generation_duration_ms}ms" if metadata.generation_duration_ms else "N/A"
    console.print(Panel(
        f"[cyan]Status:[/cyan] {metadata.status.value}\n"
        f"[cyan]Version:[/cyan] {metadata.version}\n"
        f"[cyan]Generated by:[/cyan] {metadata.generated_by}\n"
        f"[cyan]Duration:[/cyan] {duration}",
        title=f"Project: {metadata.project_name}",
        border_style="cyan"
    ))
    console.print()

    if not field or field == "overview":
        if metadata.project_overview:
            console.print(Panel(
                metadata.project_overview, title="Project Overview", border_style="green"
            ))
            console.print()

    if not field or field == "features":
        if metadata.core_features:
            console.print("[bold cyan]Core Features:[/bold cyan]")
            for feature in metadata.core_features:
                console.print(f"  [green]{feature.name}[/green]")
                console.print(f"    {feature.description}")
                if feature.key_files:
                    console.print(f"    [dim]Files: {', '.join(feature.key_files[:3])}[/dim]")
            console.print()

    if not field or field == "architecture":
        if metadata.architecture_diagram:
            console.print(Panel(
                metadata.architecture_diagram, title="Architecture", border_style="blue"
            ))
            console.print()

    if not field or field == "tech":
        if metadata.tech_stack:
            console.print("[bold cyan]Tech Stack:[/bold cyan]")
            if metadata.tech_stack.languages:
                langs = ", ".join(
                    f"{lang['name']} ({lang.get('usage_percentage', '?')}%)"
                    for lang in metadata.tech_stack.languages
                )
                console.print(f"  [cyan]Languages:[/cyan] {langs}")
            if metadata.tech_stack.frameworks:
                fws = ", ".join(f['name'] for f in metadata.tech_stack.frameworks)
                console.print(f"  [cyan]Frameworks:[/cyan] {fws}")
            if metadata.tech_stack.tools:
                console.print(f"  [cyan]Tools:[/cyan] {', '.join(metadata.tech_stack.tools)}")
            if metadata.tech_stack.build_system:
                console.print(f"  [cyan]Build System:[/cyan] {metadata.tech_stack.build_system}")
            console.print()

    if not field or field == "deps":
        if metadata.dependencies:
            total = metadata.dependencies.total_count
            console.print(f"[bold cyan]Dependencies[/bold cyan] ({total} total):")
            if metadata.dependencies.runtime:
                rt_count = len(metadata.dependencies.runtime)
                console.print(f"  [cyan]Runtime:[/cyan] {rt_count}")
            if metadata.dependencies.development:
                dev_count = len(metadata.dependencies.development)
                console.print(f"  [cyan]Development:[/cyan] {dev_count}")
            console.print()

    if not field or field == "entry":
        if metadata.entry_points:
            console.print("[bold cyan]Entry Points:[/bold cyan]")
            for ep in metadata.entry_points:
                console.print(f"  [green]{ep.path}[/green] ({ep.type})")
                console.print(f"    {ep.description}")
            console.print()

    if not field or field == "folders":
        if metadata.folder_structure:
            tree = Tree(f"[bold]{metadata.folder_structure.name}[/bold]")
            _build_folder_tree(tree, metadata.folder_structure.children)
            console.print(tree)


def _build_folder_tree(tree: Tree, children: list) -> None:
    for child in children:
        if child.type == "directory":
            subtree = tree.add(f"[blue]{child.name}/[/blue]")
            if child.children:
                _build_folder_tree(subtree, child.children)
        else:
            tree.add(f"[dim]{child.name}[/dim]")


async def run_metadata_regenerate(name: str, field: str | None = None) -> None:
    console = Console()

    try:
        async with ProjectManager() as manager:
            project = await manager.get_project(name)
    except Exception as e:
        console.print(f"[red]Error: {e}[/red]")
        console.print("[yellow]Make sure Docker containers are running.[/yellow]")
        sys.exit(1)

    if not project or not project.index_paths:
        console.print(f"[red]Project '{name}' not found in index.[/red]")
        console.print("[dim]Run 'lattice index <path>' first.[/dim]")
        sys.exit(1)

    repo_path = Path(project.index_paths[0])
    if not repo_path.exists():
        console.print(f"[red]Project path no longer exists: {repo_path}[/red]")
        sys.exit(1)

    console.print(f"[bold blue]Regenerating metadata[/bold blue] for: [cyan]{name}[/cyan]")
    if field:
        console.print(f"[dim]Field: {field}[/dim]")
    console.print()

    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        TimeElapsedColumn(),
        console=console,
    ) as progress:
        task = progress.add_task("Generating...", total=7 if not field else 1)

        def on_progress(p: GenerationProgress) -> None:
            done = len(p.completed_fields) + len(p.failed_fields)
            desc = f"Generating {p.current_field}..."
            progress.update(task, completed=done, description=desc)

        try:
            generator = MetadataGenerator(
                repo_path=repo_path,
                project_name=name,
                progress_callback=on_progress,
            )

            if field:
                result = await generator.generate_field(field)
                if result.status.value == "completed":
                    console.print(f"[green]Generated {field} successfully[/green]")
                else:
                    console.print(f"[red]Failed to generate {field}: {result.error_message}[/red]")
                    sys.exit(1)
            else:
                metadata = await generator.generate_all()

                async with PostgresClient() as postgres:
                    repository = MetadataRepository(postgres)
                    metadata.indexed_at = datetime.now()
                    await repository.upsert(metadata)

                progress.update(task, completed=7, description="Complete")

        except Exception as e:
            console.print(f"\n[red]Error: {e}[/red]")
            sys.exit(1)

    console.print()
    console.print("[green]Metadata regeneration complete![/green]")
    console.print(f"[dim]Use 'lattice metadata show {name}' to view.[/dim]")
