import json as json_module
import sys
from typing import Any

from rich.console import Console
from rich.panel import Panel
from rich.tree import Tree

from lattice.infrastructure.postgres import create_postgres_client
from lattice.metadata.api import MetadataRepository


def _build_folder_tree(tree: Tree, children: list) -> None:
    for child in children:
        if child.type == "directory":
            subtree = tree.add(f"[blue]{child.name}/[/blue]")
            if child.children:
                _build_folder_tree(subtree, child.children)
        else:
            tree.add(f"[dim]{child.name}[/dim]")


async def run_metadata_show(name: str, field: str | None = None, as_json: bool = False) -> None:
    console = Console()

    try:
        postgres = create_postgres_client()
        await postgres.connect()
        try:
            repository = MetadataRepository(postgres)
            metadata = await repository.get_by_project_name(name)
        finally:
            await postgres.close()
    except Exception as e:
        console.print(f"[red]Error connecting to PostgreSQL: {e}[/red]")
        console.print("[yellow]Make sure Docker containers are running.[/yellow]")
        sys.exit(1)

    if not metadata:
        console.print(f"[red]No metadata found for project '{name}'.[/red]")
        console.print("[dim]Run 'lattice index <path>' to generate metadata.[/dim]")
        sys.exit(1)

    if as_json:
        _print_json(console, metadata, field)
        return

    _print_rich(console, metadata, field)


def _print_json(console: Console, metadata: Any, field: str | None) -> None:
    output: dict[str, Any] = {
        "project_name": metadata.project_name,
        "version": metadata.version,
        "status": metadata.status.value,
        "generated_by": metadata.generated_by,
        "generation_model": metadata.generation_model,
        "generation_duration_ms": metadata.generation_duration_ms,
        "created_at": metadata.created_at.isoformat() if metadata.created_at else None,
        "updated_at": metadata.updated_at.isoformat() if metadata.updated_at else None,
    }

    if not field or field == "overview":
        output["project_overview"] = metadata.project_overview
    if not field or field == "features":
        output["core_features"] = [f.model_dump() for f in metadata.core_features]
    if not field or field == "architecture":
        output["architecture_diagram"] = metadata.architecture_diagram
    if not field or field == "tech":
        output["tech_stack"] = metadata.tech_stack.model_dump() if metadata.tech_stack else None
    if not field or field == "deps":
        output["dependencies"] = (
            metadata.dependencies.model_dump() if metadata.dependencies else None
        )
    if not field or field == "entry":
        output["entry_points"] = [e.model_dump() for e in metadata.entry_points]
    if not field or field == "folders":
        output["folder_structure"] = (
            metadata.folder_structure.model_dump() if metadata.folder_structure else None
        )

    console.print(json_module.dumps(output, indent=2))


def _print_rich(console: Console, metadata: Any, field: str | None) -> None:
    duration = f"{metadata.generation_duration_ms}ms" if metadata.generation_duration_ms else "N/A"
    console.print(
        Panel(
            f"[cyan]Status:[/cyan] {metadata.status.value}\n"
            f"[cyan]Version:[/cyan] {metadata.version}\n"
            f"[cyan]Generated by:[/cyan] {metadata.generated_by}\n"
            f"[cyan]Duration:[/cyan] {duration}",
            title=f"Project: {metadata.project_name}",
            border_style="cyan",
        )
    )
    console.print()

    _print_overview(console, metadata, field)
    _print_features(console, metadata, field)
    _print_architecture(console, metadata, field)
    _print_tech_stack(console, metadata, field)
    _print_dependencies(console, metadata, field)
    _print_entry_points(console, metadata, field)
    _print_folder_structure(console, metadata, field)


def _print_overview(console: Console, metadata: Any, field: str | None) -> None:
    if (not field or field == "overview") and metadata.project_overview:
        console.print(
            Panel(metadata.project_overview, title="Project Overview", border_style="green")
        )
        console.print()


def _print_features(console: Console, metadata: Any, field: str | None) -> None:
    if (not field or field == "features") and metadata.core_features:
        console.print("[bold cyan]Core Features:[/bold cyan]")
        for feature in metadata.core_features:
            console.print(f"  [green]{feature.name}[/green]")
            console.print(f"    {feature.description}")
            if feature.key_files:
                console.print(f"    [dim]Files: {', '.join(feature.key_files[:3])}[/dim]")
        console.print()


def _print_architecture(console: Console, metadata: Any, field: str | None) -> None:
    if (not field or field == "architecture") and metadata.architecture_diagram:
        console.print(
            Panel(metadata.architecture_diagram, title="Architecture", border_style="blue")
        )
        console.print()


def _print_tech_stack(console: Console, metadata: Any, field: str | None) -> None:
    if (not field or field == "tech") and metadata.tech_stack:
        console.print("[bold cyan]Tech Stack:[/bold cyan]")
        if metadata.tech_stack.languages:
            langs = ", ".join(
                f"{lang['name']} ({lang.get('usage_percentage', '?')}%)"
                for lang in metadata.tech_stack.languages
            )
            console.print(f"  [cyan]Languages:[/cyan] {langs}")
        if metadata.tech_stack.frameworks:
            fws = ", ".join(f["name"] for f in metadata.tech_stack.frameworks)
            console.print(f"  [cyan]Frameworks:[/cyan] {fws}")
        if metadata.tech_stack.tools:
            console.print(f"  [cyan]Tools:[/cyan] {', '.join(metadata.tech_stack.tools)}")
        if metadata.tech_stack.build_system:
            console.print(f"  [cyan]Build System:[/cyan] {metadata.tech_stack.build_system}")
        console.print()


def _print_dependencies(console: Console, metadata: Any, field: str | None) -> None:
    if (not field or field == "deps") and metadata.dependencies:
        total = metadata.dependencies.total_count
        console.print(f"[bold cyan]Dependencies[/bold cyan] ({total} total):")
        if metadata.dependencies.runtime:
            console.print(f"  [cyan]Runtime:[/cyan] {len(metadata.dependencies.runtime)}")
        if metadata.dependencies.development:
            console.print(f"  [cyan]Development:[/cyan] {len(metadata.dependencies.development)}")
        console.print()


def _print_entry_points(console: Console, metadata: Any, field: str | None) -> None:
    if (not field or field == "entry") and metadata.entry_points:
        console.print("[bold cyan]Entry Points:[/bold cyan]")
        for ep in metadata.entry_points:
            console.print(f"  [green]{ep.path}[/green] ({ep.type})")
            console.print(f"    {ep.description}")
        console.print()


def _print_folder_structure(console: Console, metadata: Any, field: str | None) -> None:
    if (not field or field == "folders") and metadata.folder_structure:
        tree = Tree(f"[bold]{metadata.folder_structure.name}[/bold]")
        _build_folder_tree(tree, metadata.folder_structure.children)
        console.print(tree)
